name: Reusable Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Environment to deploy to (dev, staging, prod)'
    secrets:
      AZURE_CLIENT_ID:
        required: true
        # type: string
        description: 'Azure User Assigned Identity Client ID'
      TENANT_ID:
        required: true
        # type: string
        description: 'Azure Tenant ID'
      SUB_ID:
        required: true
        # type: string
        description: 'Azure Subscription ID'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build and Publish
        run: dotnet publish DGC.eKYC.Api/DGC.eKYC.Api.csproj -c Release -o ./publish

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUB_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          # This variable comes from the GitHub Environment configuration
          # app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          app-name: 'azureweb'
          package: ./publish